apiVersion: v1
kind: Service
metadata:
    name: demo-service-service
spec:
    #target any pod with template.labels=app:configuration-service-deployment
    selector:
        app: demo-service-deployment
    #type: default is ClusterIP  from inside the cluster
    ports:
    - protocol: TCP
      port: 8080
      #nodePort: 30001 #available to outside of the cluster <NodeIP>:<NodePort>
  #type: NodePort